default_language_version:
  python: python3

# NOTE: Update in .flake8 pyproject.toml as well
exclude: |
    (?x)^(
      \.git|
      __pycache__|
      \.venv
    )

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        args: [--unsafe]
        exclude: ^helm/templates/
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: detect-private-key
      - id: name-tests-test
        args: [--pytest-test-first]
        exclude: ^tests/utils/stac_io_mock.py
      - id: debug-statements
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=100]

  # Run the Ruff linter.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.8
    hooks:
      # Linter
      - id: ruff
        types_or: [python, pyi, jupyter, toml]
        args: [--fix, --exit-non-zero-on-fix]
      # Formatter
      - id: ruff-format
        types_or: [python, pyi, jupyter, toml]

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.396
    hooks:
      - id: pyright
        verbose: true  # FIXME: Remove me after fixing all issues
        entry: bash -c 'pyright "$@" || true' --  # FIXME: Remove me after fixing all issues
        additional_dependencies:
          [
            beartype,
            einops,
            jax,
            jaxtyping,
            optax,
            pytest,
            typing_extensions,
            wadler_lindig,
          ]
