name: Lints

on:
  pull_request:
  push:
    branches:
      - main


jobs:
  pre_commit_checks:
    name: Pre-Commit checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - uses: pre-commit/action@main
